bot_token: "XXX"
gemini_api_key: "XXX"
developer_chat_id: XXX

gemini_model:
  model_name: "gemini-2.0-flash"
  temperature: 0.7
  stop_sequences: null
  max_output_tokens: null
  top_p: null
  top_k: null
  safety_settings: null
  tools: null

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

bot_messages:
system_prompt: "You are Aurora, an intelligent and empathetic personal assistant. Analyze the image and provide a detailed description."
welcome_message: "Hello! I'm your Personal Assistant Bot, now powered by the Gemini Model!"
help_message: "I'm your Personal Assistant Bot, now powered by Gemini!\nType in any questions or requests and I'll use Gemini to help you.\nCommands:\n/start - Start the bot and display the welcome message.\n/help - Display this help message."

database:
  db_path: "chat_memory.db"
  short_term_limit: 10
  top_k: 3

embedding_model:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"

commands:
  start: "start"
  help: "help"